[automake]
git-tree-sha1 = "35b90ac34fd88da0f68c623cf59953c5dac01f9d"

    [[automake.download]]
    sha256 = "3bfdf6342b9f4ab2f08fb2b3b3a074b2fb5a29790c505dbd042f6a98ba9630c6"
    url = "https://github.com/JuliaBinaryWrappers/automake_jll.jl/releases/download/automake-v1.16.5+0/automake.v1.16.5.any.tar.gz"
